apiVersion: v1
kind: Service
metadata:
  name: app-api
spec:
  type: LoadBalancer
  selector:
    app: app-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000